version: '3.4'

services:
  recall-seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "35340:80"
  
  recall-sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "35433:1433"
    volumes:
      - recall-sqldata:/var/opt/mssql


  recall-textlist.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "35210:80"

  recall-envoygateway:
    volumes:
      - ./Infrastructure/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "35191:80"
      - "35181:8001"

  recall-servicestatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "35107:80"


volumes:
  recall-sqldata:
    external: false